---
- hosts: all
  become: true
  tasks:

    - name: Install apache and php
      apt:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
      


